version: '3.8'
services:

    magento:
        build:
            context: ./docker
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: magento
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            XDEBUG_MODE: '${magento_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${magento_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html/magento'
        networks:
            - magento
        depends_on:
            - mariadb
            - opensearch

    mariadb:
        image: 'mysql:8'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'yousef'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: 'magento'
            MYSQL_USER: 'yousef'
            MYSQL_PASSWORD: 'yousef'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'mariadb:/var/lib/mysql'
        networks:
            - magento

#    opensearch:
#      restart: always
#      image: opensearchproject/opensearch:2.5.0
#      environment:
#        - "discovery.type=single-node"
#        - "cluster.routing.allocation.disk.threshold_enabled=false"
#        - "index.blocks.read_only_allow_delete"
#      env_file: docker/opensearch.env
#      volumes:
#        - "opensearch:/usr/share/opensearch/data"
#      ports:
#        - 9200:9200
#        - 9600:9600 # required for Performance Analyzer
#      networks:
#        - magento
#
#    kibana1:
#      container_name: kibana
#      image: docker.elastic.co/kibana/kibana:8.4.0
#      restart: always
#      environment:
#        - ELASTICSEARCH_HOSTS=http://opensearch:9200    # address of elasticsearch docker container which kibana will connect
#      ports:
#        - 5601:5601
#      depends_on:
#        - opensearch

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
      container_name: elasticsearch
      restart: always
      environment:
        - xpack.security.enabled=false
        - discovery.type=single-node
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65536
          hard: 65536
      cap_add:
        - IPC_LOCK
      volumes:
        - "elasticsearch:/usr/share/elasticsearch/data"
      ports:
        - 9200:9200
      networks:
        - magento


    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:7.17.0
        restart: always
        environment:
          - ELASTICSEARCH_HOSTS=http://elasticsearch:9200    # address of elasticsearch docker container which kibana will connect
        ports:
          - 5601:5601
        depends_on:
          - elasticsearch
        networks:
          - magento

networks:
    magento:
        driver: bridge

volumes:
    mariadb:
        driver: local
    elasticsearch:
        driver: local
